# manifest.toml - gsettings-desktop-schemas (syshub tier)

[package]
name             = "gsettings-desktop-schemas"
version          = "49.1"
description      = "Shared GSettings schemas for the GNOME desktop"
license          = "LGPL-2.1-or-later"
maintainer       = "Ali Zain <alizain@zainiumdynamics.tech>"
homepage         = "https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["glib"]
provides         = ["gsettings-desktop-schemas"]
tags             = ["gnome", "desktop", "schemas"]

[install]
share   = "/overlayer/syshub/share"
_syshub = true

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
