# manifest.toml - gnome-commander (syshub tier)

[package]
name             = "gnome-commander"
version          = "1.18.6"
description      = "Graphical twin-panel file manager"
license          = "GPL-2.0-only"
maintainer       = "Ali Zain <alizain@zainiumdynamics.tech>"
homepage         = "https://gnome.pages.gitlab.gnome.org/gnome-commander/"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["glib", "gtk3", "gdk-pixbuf"]
provides         = ["gnome-commander"]
tags             = ["gnome", "file-manager", "app"]

[install]
bin     = "/overlayer/syshub/bin"
share   = "/overlayer/syshub/share"
_syshub = true

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
